<template>
    <main>
        <courses-our-courses/>
        <courses-explorer/>
        <courses-course-banner/>
        <courses-our-programs/>
        <courses-course-metodology/>
        <courses-gift-knowledge/>
    </main>
</template>